version: '3.8'
services:
  redis:
    container_name: redis_container
    image: redis:8.4.0-alpine
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--loglevel", "warning"]  
    volumes: 
      - ./docker-volumes/redis:/data

  mongo:
    container_name: mongodb_container
    image: mongo:8.2.3
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./docker-volumes/mongodb:/data/db

  mysql:
    container_name: mysql_container
    image: mysql:9.5.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=jobapp
      - MYSQL_DATABASE=jobapp
      - MYSQL_PASSWORD=jobapp123
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql

  postgres:
    container_name: postgres_container
    image: postgres:18.1
    restart: always
    environment:
      - POSTGRES_USER=jobapp
      - POSTGRES_DB=jobapp
      - POSTGRES_PASSWORD=jobapp123
    ports:
      - "5432:5432"
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql   

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:4.2.2-management-alpine
    restart: always
    ports:
      # AMQP port
      - "5672:5672"
      # Management UI port
      - "15672:15672"

  elasticsearch:
    container_name: elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.4
    restart: always
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.authc.api_key.enabled=true
      - xpack.monitoring.collection.enabled=true
      - xpack.security.enrollment.enabled=true
    ports:
      # Elasticsearch ports
      - "9200:9200"
      # Transport port  
      - "9300:9300"   
    volumes:
      - ./docker-volumes/elasticsearch:/usr/share/elasticsearch/data   
    networks:
      - elastic_network

  networks:
    elastic:
      name: elastic_network    